# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mutualfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=50)),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('acquired_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_number', models.IntegerField()),
                ('lname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('vol_dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('cell_phone', models.CharField(max_length=50)),
                ('vol_notes', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='mutualfund',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Mutualfund',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
