# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180319_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
