# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_client_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
